---
- name: This is SSH Key Authentication
  hosts: all
  become: yes
  tasks:
    - name: Generate an OpenSSH rsa keypair with a different size (2048 bits)
      community.crypto.openssh_keypair:
        path: /home/centos/.ssh/id_rsa
        type: rsa
        size: 2048
